# Generated by Django 2.2.10 on 2020-06-10 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200610_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alias',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 13, 1, 4, 573257), verbose_name='Дата заказа'),
        ),
    ]
