# Generated by Django 2.2.10 on 2020-06-11 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200610_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 9, 41, 8, 519822), verbose_name='Дата заказа'),
        ),
    ]
