# Generated by Django 2.2.10 on 2020-06-11 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200611_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 9, 43, 41, 423246), verbose_name='Дата заказа'),
        ),
    ]
