# Generated by Django 2.2.10 on 2020-06-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200611_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(max_length=250, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(verbose_name='Дата заказа'),
        ),
    ]
