# Generated by Django 2.2.10 on 2020-06-17 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200613_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.CharField(default=123, max_length=20, unique=True, verbose_name='Уникальный номер заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата заказа'),
        ),
    ]
