# Generated by Django 2.2.10 on 2020-06-17 01:46

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200617_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(max_length=20, unique=True, verbose_name='Уникальный номер заказа'),
        ),
    ]
