# Generated by Django 2.2.10 on 2020-06-17 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200617_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_add'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_add'], 'verbose_name': 'Отыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='points',
        ),
        migrations.AddField(
            model_name='article',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания статьи'),
        ),
        migrations.AddField(
            model_name='review',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата добавления отзыва'),
        ),
    ]
