# Generated by Django 2.2.13 on 2020-06-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200622_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(max_length=250, upload_to='img', verbose_name='Фото'),
        ),
    ]
